# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  initial_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: give status
        run: echo "Got the files"
  build:
    needs: initial_job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ENV_KEY: noodle
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: cat james.txt
      - name: Get Env
        run: echo $ENV_KEY
        
